{{- $root := . -}}

{{ range $k, $v := until ( int $root.Values.participant.replicas) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ $root.Values.namespace.name }}-{{$v}}-sa"
  namespace: "{{ $root.Values.namespace.name }}-{{$v}}"
automountServiceAccountToken: false
{{- end}}