{{- $root := . -}}

{{ range $k, $v := until ( int $root.Values.participant.replicas) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "kube-system-{{$v}}-role"
  namespace: "kube-system"
rules:
  - apiGroups: ["", "extensions","apps","autoscaling","batch","apiextensions.k8s.io","acid.zalan.do","elasticsearch.k8s.elastic.co"]
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
{{- end}}
