{{- $root := . -}}

{{ range $k, $v := until ( int $root.Values.participant.replicas) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ $root.Values.namespace.name }}-{{$v}}-role-binding-kube-system"
  namespace: "kube-system"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "kube-system-{{$v}}-role"
subjects:
  - kind: ServiceAccount
    name: "{{ $root.Values.namespace.name }}-{{$v}}-sa"
    namespace: "kube-system"
{{- end}}
