# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#  name: {{ .Values.participant.volumeClaimTemplates.storage.className }}
# # provisioner: kubernetes.io/azure-file
# provisioner: file.csi.azure.com
# mountOptions:
# - dir_mode=0777
# - file_mode=0777
# - uid=0
# - gid=0
# - mfsymlinks
# - cache=strict
# - actimeo=30
# parameters:
#  skuName: Standard_LRS
# #  storageAccount: drapodstorage
# volumeBindingMode: WaitForFirstConsumer



# ----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.participant.volumeClaimTemplates.storage.className }}
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
volumeBindingMode: WaitForFirstConsumer








#---

#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: {{ .Values.participant.volumeClaimTemplates.storage.className }}
##provisioner: file.csi.azure.com
#provisioner: kubernetes.io/azure-file
#parameters:
#  skuName: Standard_LRS
#  location: westeurope
#  storageAccount: drapodstorage
#  secretNamespace: default
#  secretName: storage-secret
#  resourceGroup: MC_dra_draaks_westeurope
#volumeBindingMode: WaitForFirstConsumer




# -----
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#  name: {{ .Values.participant.volumeClaimTemplates.storage.className }}
# provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
# allowVolumeExpansion: true
# mountOptions:
#  - dir_mode=0755
#  - file_mode=0755
#  - uid=0
#  - gid=0
#  - mfsymlinks
#  - cache=strict
#  - actimeo=30
# parameters:
#  skuName: Premium_LRS
#  location: westeurope
#  storageAccount: drapodstorage
#  secretName: storage-secret
#  secretNamespace: default
# volumeBindingMode: WaitForFirstConsumer







