- job_name: 'blackbox-tcp'
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /probe
  params:
    module: [tcp_connect_v4]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: target
    - target_label: __address__
      replacement: prometheus-blackbox-exporter:9115
  static_configs:
  - targets:
