- job_name: 'blackbox-tcp'
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /probe
  params:
    module: [tcp_connect]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: target
    - target_label: __address__
      replacement: blackbox-exporter.monitoring:19115
  static_configs:
  - targets:
