name: Terraform plan

on:
  workflow_dispatch:
    inputs:

      labName:
        description: The name of the lab
        required: true
        default: "mva"

      labNumberParticipants:
        description: The number of participants in the lab
        required: true
        default: "20"

      nodeCount:
        description: The number of nodes to create
        required: true
        default: "3"

      vmSizeAks:
        description: The size of the AKS VM
        required: true
        default: "Standard_E8_v3"

  push:
    branches:
      - main
      - actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform plan
        env:
          TF_ACTION: 'plan' #${{ github.event.inputs.tfAction }}

          TF_VAR_labname: ${{ github.event.inputs.labName }}
          TF_VAR_location: ${{ secrets.LOCATION }}
          TF_VAR_labNumberParticipants: ${{ github.event.inputs.labNumberParticipants }}
          TF_VAR_vmSizeAks: ${{ github.event.inputs.vmSizeAks }}
          TF_VAR_nodecount: ${{ github.event.inputs.nodeCount }}
          TF_VAR_clientid: ${{ secrets.ARM_CLIENT_ID }}
          TF_VAR_clientsecret: ${secrets.ARM_CLIENT_SECRET }}
          TF_VAR_rsgcommon: ${{ secrets.RSGCOMMON }}
          
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          STATE_BLOBACCESSKEY: ${{ secrets.STATE_BLOBACCESSKEY }}

          ZIPPASS: ${{ secrets.ZIPPASS }}
          SSHUSERPW: ${{ secrets.SSHUSERPW }}
          RSGCOMMON: ${{ secrets.RSGCOMMON }}
          LOCATION: ${{ secrets.LOCATION }}
          LABNAMEINVENTORYSTORAGEACCOUNT: ${{ secrets.LABNAMEINVENTORYSTORAGEACCOUNT }}
          HUGOVERSION: ${{ secrets.HUGOVERSION }}

        run: |
          #!/bin/bash
          set -e
          set -x

          if [ -z "$TF_VAR_labname" ] ;
          then
              echo "environmentname is unset" ;
              exit 1;
          fi

          if [[ $TF_ACTION != "plan" ]];then
            TF_OPTIONS="--auto-approve"
          fi

          docker run \
                  -v "$(pwd)"/:/workspace \
                  -w /workspace \
                  hashicorp/terraform:latest \
                      init \
                          -backend-config="key=${TF_VAR_labname}-components.tfstate" \
                          -backend-config="access_key=$(STATE_BLOBACCESSKEY)" \
                          -backend-config=storage_account_name="${STATE_SAACCOUNTNAME}"

          docker run \
                  -e ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID) \
                  -e ARM_CLIENT_ID=$(ARM_CLIENT_ID) \
                  -e ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET) \
                  -e ARM_TENANT_ID=$(ARM_TENANT_ID) \
                  -e STATE_BLOBACCESSKEY=$(STATE_BLOBACCESSKEY) \
                  -e TF_VAR_labname=$TF_VAR_labname \
                  -e TF_VAR_location=$TF_VAR_location \
                  -e TF_VAR_labNumberParticipants=$TF_VAR_labNumberParticipants \
                  -e TF_VAR_vmSizeAks=$TF_VAR_vmSizeAks \
                  -e TF_VAR_nodecount=$TF_VAR_nodecount \
                  -e TF_VAR_clientid=$(ARM_CLIENT_ID) \
                  -e TF_VAR_clientsecret=$(ARM_CLIENT_SECRET) \        
                  -e TF_VAR_rsgcommon=$(rsgcommon) \
                  -v "$(pwd)"/:/workspace \
                  -w /workspace \
                  hashicorp/terraform:latest \
                      $TF_ACTION \
                      $TF_OPTIONS
        working-directory: 'infrastructureAsCode'